server: 
  port: 3344 
  
spring:
  application:
    name:  microservicecloud-config
  cloud:
    config:
      server:
        git:
          uri: https://github.com/zxf2672940666/microservicecloud-config.git #GitHub上面的git仓库名字

 

